Bugfix/comment duplication
rust-lang/rustfmt pull request #5913
Opened 2023-09-16 19:28 UTC by GambitingMan

Fixes #5871 

The issue  was in the `rewrite_paren` function.

Since the span on expressions doesn't include attributes and attributes comes before the expression, this caused the attribute to be included in `pre_comment` since the end of the comment span was `subexpr.span.lo()`.
I changed the logic to use the span of the first attribute, if there are any attributes present. If not, default to the expression span.

2023-09-16 21:21 UTC, calebcartwright requested changes
Thanks for the PR! You've definitely identified the root cause, as well as the proper underlying technique to address the issue.

However, this is such a common type of occurrence that we've got existing utilities that can and should be reused here instead. Details linked below, but basically using our `span()` instead of the AST struct's `span` field will cover the inline logic you originally proposed

https://github.com/rust-lang/rustfmt/blob/da7f67810f263351f61f5618c250f7396a5f9bbc/src/spanned.rs#L43-L55

2023-09-16 21:21 UTC, calebcartwright commented on src/expr.rs
> +        pre_span = mk_sp(span.lo() + BytePos(1), expr_lo);
```suggestion
        pre_span = mk_sp(span.lo() + BytePos(1), subexpr.span().lo());
```

2023-09-17 07:01 UTC, GambitingMan commented
That did the trick :smile:

2023-09-20 19:28 UTC, calebcartwright commented
Thanks for fixing this and for your first contribution!

2023-09-20 19:29 UTC, merged