Issue 6202
rust-lang/rustfmt pull request #6224
Opened 2024-06-30 22:00 UTC by CalebLItalien

This closes #6202 .

2024-07-01 16:09 UTC, ytmimi requested changes
Let's add a comment to the code and reduce the test case down to the minimum configs needed to reproduce the issue.

2024-07-01 16:09 UTC, ytmimi commented on tests/source/issue-6202/issue_example.rs
> +// rustfmt-version: Two
Although the user provided us with all of their configs, I think it's only the `max_width` setting that we need to reproduce the error. Could you trim this down to only include the relevant configs.

2024-07-01 16:09 UTC, ytmimi commented on src/expr.rs
> +        pat_shape = pat_shape.sub_width(2)?;
Let's leave a comment explaining why we're subtracting 2 from the width. Something like `// 2 for the length of " ="` should do.

2024-07-01 21:13 UTC, ytmimi requested changes
Just a minor nit and then I think we're good to go. Also, can you please squash all these commits and then rebase on the latest master. The team strongly discourages merge commits in PRs.

2024-07-01 21:13 UTC, ytmimi commented on src/expr.rs
> +        pat_shape = pat_shape.sub_width(2)?; // 2 to account for the length of " ="
Nit: I'd prefer the comment to be above the line like we do in most other explanatory comments within the codebase.

2024-07-04 00:38 UTC, CalebLItalien commented
Apologies, was trying to squash the recent merge commit and accidentally reset the branch. I have a backup and will open a new PR.

2024-07-04 00:38 UTC, CalebLItalien commented
Apologies, was trying to squash the recent merge commit and accidentally reset the branch. This reopens the PR.

2024-07-04 02:24 UTC, ytmimi commented
The git history seems off to me. I think you might have squashed too many commits or grabbed the wrong commit message somehow?

2025-01-31 06:34 UTC, vats004 commented
hey can I work on this issue

2025-01-31 14:31 UTC, ytmimi commented
@vats004 Sure! You can create a nearly identical PR. The only difference is that we'll need to gate this change on `StyleEdition::Edition2027`, instead of `Version::Two`.

2025-01-31 15:18 UTC, ytmimi commented
> What's the rationale for gating a clear bugfix behind a future edition?

rustfmt has a strong stability guarantee

2025-05-31 15:13 UTC, closed without merging

2025-05-31 15:13 UTC, ytmimi commented
Closing since #6572 was merged instead