config_proc_macro: reduce syn's features
rust-lang/rustfmt pull request #6237
Opened 2024-07-11 09:03 UTC by klensy

This reduces syn's features to 'full' only for that proc macro.

2024-07-30 01:46 UTC, dtolnay requested changes
These are not sufficient features for this macro. When I build this, I get:

```console
error[E0432]: unresolved import `syn::parse_macro_input`
   --> config_proc_macro/src/lib.rs:14:5
    |
14  | use syn::parse_macro_input;
    |     ^^^^^^^^^^^^^^^^^^^^^^ no `parse_macro_input` in the root
    |
note: found an item that was configured out
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syn-2.0.72/src/lib.rs:465:5
    |
465 | mod parse_macro_input;
    |     ^^^^^^^^^^^^^^^^^
note: the item is gated here
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syn-2.0.72/src/lib.rs:464:1
    |
464 | #[cfg(all(feature = "parsing", feature = "proc-macro"))]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

and many other errors.

2024-07-30 11:10 UTC, klensy commented
Hmm, yes, this shouldn't work, but locally compiles. Something somewhere merging features?
```
$ pwd
/g/projs/rustfmt/config_proc_macro
```
```
$ cargo b
   Compiling proc-macro2 v1.0.63
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.26
   Compiling syn v2.0.14
   Compiling rustfmt-config_proc_macro v0.3.0 (G:\projs\rustfmt\config_proc_macro)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.25s
```

```
$ cargo tree -p syn -i -e features,normal
syn v2.0.14
`-- syn feature "full"
    `-- rustfmt-config_proc_macro v0.3.0 (proc-macro) (G:\projs\rustfmt\config_proc_macro)
        `-- rustfmt-config_proc_macro feature "default" (command-line)
```
`/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syn-2.0.72/` aha, so you at least bumped deps here, is there any more chages?

2024-07-30 11:21 UTC, klensy commented
Bumping edition to 2021 allowed to discover actually wrong feature set of features.

2024-09-12 04:41 UTC, ytmimi approved these changes
Thanks!

Edit: [Diff-Check](https://github.com/rust-lang/rustfmt/actions/runs/10824579438) passed ✅

2024-09-12 05:31 UTC, merged